[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate --schema=./schema.prisma && npx tsc"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
